### ISSUE TITLE
Uncaught Error: This TextEditor has been destroyed

### ISSUE THREAD

**Issue by panesofglass** [ionide/ionide-atom-fsharp#126]
[Enter steps to reproduce below:]
1. Opened Atom with a script.fsx file
2. Attempted to execute FSI: Send File

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-fsharp](https://github.com/fsprojects/atom-fsharp) package, v0.13.0
### Stack Trace

Uncaught Error: This TextEditor has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:773

Error: This TextEditor has been destroyed
  at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1097:15)
  at Marker.module.exports.Marker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:179:33)
  at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:90:26)
  at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:708:20)
  at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:713:51)
  at Selection.module.exports.Selection.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:951:28)
  at Selection.module.exports.Selection.clear (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:198:14)
  at Selection.module.exports.Selection.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:452:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:745:29
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:787:29
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:768:18)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1168:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:781:24
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2037:18)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1999:35)
  at TextEditor.module.exports.TextEditor.mutateSelectedText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:779:19)
  at TextEditor.module.exports.TextEditor.insertText (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:742:19)
  at TextEditor.object.(anonymous function) [as insertText] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/underscore-plus/lib/underscore-plus.js:77:27)
  at /Users/ryan/.atom/packages/atom-fsharp/lib/fsharp.js:2542:28
  at Option__Iterate$IEditor_IEditor_ (/Users/ryan/.atom/packages/atom-fsharp/lib/fsharp.js:3797:14)
  at Interactive__sendToFsi$ (/Users/ryan/.atom/packages/atom-fsharp/lib/fsharp.js:2540:7)
  at Interactive__sendFile$ (/Users/ryan/.atom/packages/atom-fsharp/lib/fsharp.js:2509:5)
  at atom-text-editor.<anonymous> (/Users/ryan/.atom/packages/atom-fsharp/lib/fsharp.js:2396:14)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -0:30.7.0 command-palette:toggle (div.settings-view.pane-item)
     -0:28.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28.4.0 FSI:Open (div.settings-view.pane-item)
     -0:04.8.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:03.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.8.0 FSI:Send-File (atom-text-editor.editor.vim-mode.normal-mode)
```
### Config

``` json
{
  "core": {
    "projectHome": "/Users/ryan/Code",
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "._*",
      "Thumbs.db",
      "bin",
      "obj"
    ]
  },
  "atom-fsharp": {
    "MonoPath": "/Library/Frameworks/Mono.framework/Versions/Current/bin"
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
Paket, v1.0.2
atom-fsharp, v0.13.0
atom-typescript, v6.0.2
atom-yeoman, v0.3.13
json-schema, v0.1.13
linter, v1.5.0
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by Krzysztof-Cieslak** [comment]
Is FSI panel working at all? (standard FSI text showing in the panel? )

Is sending text line-by-line or by selection working?

Also, if You tried it just after update, can you try it again after restarting Atom - sometimes there are problems with recovering after update.

Last thing to check would be disabling `vim-mode` plugin and trying again

**Comment by panesofglass** [comment]
Yes, I tried restarting Atom. Today, I can see the FSI panel, but nothing is ever executed. I'll try disabling vim-mode.

**Comment by panesofglass** [comment]
Disabling vim-mode works but makes Atom unusable for me. :(
